---
layout: home
title: Welcome to Dalton Fontes' Blog
description: A personal blog about tech, coding, and life.
---

# Welcome to My Blog

Hello! I'm Dalton Fontes, and this is my personal blog where I share my thoughts on technology, coding, and various aspects of life.

## Recent Posts

<ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
      <span>{{ post.date | date: "%B %d, %Y" }}</span>
    </li>
  {% endfor %}
</ul>

Feel free to explore and connect with me on [GitHub](https://github.com/daltonfontes) and [LinkedIn](https://linkedin.com/in/daltonfontes)!
